version: '3.8'

services:
  web:
    build: .
    command: ./bin/rails s -b 0.0.0.0
    ports:
      - "3000:3000"
      - "1237:1237"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    tty: true
    stdin_open: true
    environment:
      - RUBY_DEBUG_OPEN=true
