version: '3.8'

services:
  web:
    build: .
    command: ./bin/rails s -b 0.0.0.0
    ports:
      - "3000:3000"
      - "1237:1237"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    tty: true
    stdin_open: true
    environment:
      - WEB_CONCURRENCY=3
      - RUBY_DEBUG_OPEN=true
      # - RUBY_DEBUG_PORT=1237
      # - RUBY_DEBUG_HOST=0.0.0.0
      # - RUBY_DEBUG_FORK_MODE=parent
      # - RUBY_DEBUG_ADDED_RUBYOPT='-r debug/...'
    # volumes:
    #   - .:/app
